config/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from web.sitemaps import (BlogSitemap, ContactPageSitemap, DeliveryPageSitemap,
                          DoorSitemap, HomePageSitemap, CatalogSitemap)

handler404 = 'web.views.custom_404_view'

sitemaps = {
    'blogs': BlogSitemap,
    'doors': DoorSitemap,
    'index': HomePageSitemap,
    'contact': ContactPageSitemap,
    'delivery': DeliveryPageSitemap,
    'catalog': CatalogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('captcha/', include('captcha.urls')),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('contacts/', views.contact, name='contact'),
    path('compare/', views.compare_doors, name='compare_doors'),
    path('delivery/', views.delivery, name='delivery'),
    path(
        'delivery/<slug:slug>/',
        views.delivery_detail,
        name='delivery_detail'
    ),
    path('installation/', views.installation, name='installation'),
    path('garant/', views.garant, name='garant'),
    path('calc/', views.calculator, name='calculator'),
    path('shop_card/', views.shop_card, name='shop_card'),
    path('reviews/', views.reviews, name='reviews'),
    path('detail/<slug:slug>/', views.door_detail, name='door_detail'),
    path('catalog/', views.catalog, name='catalog'),
    path('catalog/<slug:slug>/', views.catalog, name='catalog_with_slug'),
    path('blog/', views.blog_chapter, name='blog_chapter'),
    path(
        'blog/<slug:chapter_slug>/',
        views.blog_chapter_detail,
        name='blog_chapter_detail'
    ),
    path(
        'blog/<slug:chapter_slug>/<slug:post_slug>/',
        views.blog_post_detail,
        name='blog_post_detail'
    ),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

web/models.py
import uuid

from ckeditor.fields import RichTextField
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from slugify import slugify


class BlogChapter(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='chapter')
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, separator='-')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=255)
    chapter = models.ForeignKey(
        BlogChapter,
        on_delete=models.CASCADE,
        related_name='blogs'
    )
    content = RichTextField()
    image = models.ImageField(upload_to='blog')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, separator='-')
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_post_detail', args=[self.chapter.slug, self.slug])

    def __str__(self):
        return self.title


class DeliveryRegion(models.Model):

    REGION_CHOICES = [
        ('moscow', 'Москва'),
        ('moscow_region', 'Московская область'),
    ]

    name = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to='delivery_region',
        blank=True
    )
    slug = models.SlugField(max_length=255, unique=True)
    region = models.CharField(
        max_length=20,
        choices=REGION_CHOICES,
        default='moscow_region',
        verbose_name='Регион'
    )
    text = models.TextField(blank=True)
    cost = models.IntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, separator='-')
        super().save(*args, **kwargs)

    class Meta:
        pass


class CallBack(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=18)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.pk is None:
            super(CallBack, self).save(*args, **kwargs)  # Сначала сохраняем объект

            # Отправка email уведомления
            send_mail(
                'Обратный звонок',
                f'Была создана новая заявка [обратный вызов] от {self.name}.\nТелефон: {self.phone}',
                settings.DEFAULT_FROM_EMAIL,  # От кого
                ['4109974@inbox.ru'],  # Кому отправляем (ваша же почта)
                fail_silently=False,
            )
        else:
            super(CallBack, self).save(*args, **kwargs)


class Catalog(models.Model):
    title = models.CharField(max_length=255)
    chapter = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(
        upload_to='catalog',
        null=True,
        blank=True
    )
    description = models.CharField(max_length=150, null=True, blank=True)
    content = models.TextField(default='')
    custom_h1 = models.CharField(max_length=256, default='Входные металлические {{ catalog.title|lower }} двери')
    custom_title = models.CharField(max_length=150, null=True, blank=True)

    def get_door_count(self):
        """Возвращает количество дверей, связанных с данной категорией."""
        return self.catalogs.count()

    def get_absolute_url(self):
        return reverse('catalog_with_slug', kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return f"{self.title} из '{self.chapter}'"


class Tag(models.Model):
    TEXT_COLOR_CHOICES = [
        ('dark', 'Dark'),
        ('light', 'Light'),
    ]

    text_color = models.CharField(
        max_length=10,
        choices=TEXT_COLOR_CHOICES,
        default='dark',
        help_text='Выбор цвета текста'
    )
    title = models.CharField(max_length=255, unique=True)
    color_hex = models.CharField(
        max_length=7,
        help_text='Введите цвет в формате #RRGGBB'
    )

    def __str__(self) -> str:
        return f"{self.title} [{self.color_hex}]"


class Review(models.Model):
    RATING_CHOICES = [(i, i) for i in range(11)]

    name = models.CharField(max_length=255)
    order = models.OneToOneField(
        'Order',
        on_delete=models.CASCADE,
        related_name='review',
        null=True
    )
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)
    message = models.CharField(max_length=1024, null=True, blank=True)

    def __str__(self):
        return f'От {self.name} [{self.order}]: Рейтинг {self.rating}'


class Door(models.Model):
    title = models.CharField(max_length=255)
    article = models.CharField(max_length=255)
    price = models.IntegerField()
    purpose = models.CharField(max_length=255)
    conturs_name = models.CharField(max_length=255)
    size_name = models.CharField(max_length=255)
    steel_size = models.CharField(max_length=255)
    tolshina = models.CharField(max_length=255)
    korob_size = models.CharField(max_length=255)
    uteplitel = models.CharField(max_length=255)
    ves = models.CharField(max_length=255)
    constr_korob = models.CharField(max_length=255)
    constr_fixator = models.CharField(max_length=255)
    zamok1 = models.CharField(max_length=255)
    zamok2 = models.CharField(max_length=255)
    furn_color_name = models.CharField(max_length=255)
    petli = models.CharField(max_length=255)
    zadvijka = models.CharField(max_length=255)
    ruchka = models.CharField(max_length=255)
    glazok = models.CharField(max_length=255)
    cilindr = models.CharField(max_length=255)
    bronia = models.CharField(max_length=255)
    out_cover_name = models.CharField(max_length=255)
    out_color = models.CharField(max_length=255)
    in_cover_name = models.CharField(max_length=255)
    in_thick = models.CharField(max_length=255)
    in_color = models.CharField(max_length=255)
    images = models.TextField()
    discount = models.PositiveSmallIntegerField(null=True, default=0)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name='doors', blank=True)
    catalogs = models.ManyToManyField(
        Catalog,
        related_name='catalogs',
        blank=True
    )
    equipment = models.CharField(max_length=1024*1024)
    description = models.CharField(max_length=255, blank=True)
    catalogs_cloud = models.ManyToManyField(
        Catalog,
        related_name='catalogs_cloud',
        blank=True
    )
    hidden = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    h1 = models.CharField(max_length=256, blank=True)
    description = models.CharField(max_length=512, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.title, separator='-')
            self.slug = slug
        if not self.description:
            self.description = f'Купить дверь {self.title}, недорого'
        super().save(*args, **kwargs)

    def get_reviews(self):
        """Возвращает все отзывы, связанные с дверью через заказы."""
        return Review.objects.filter(order__door=self)

    def get_order_count(self):
        return self.orders.count()

    def get_absolute_url(self):
        return reverse('door_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Order(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    call_time = models.DateTimeField()
    address = models.CharField(max_length=512)
    message = models.TextField()
    order_number = models.CharField(
        max_length=255,
        unique=True,
        editable=False,
        blank=True
    )
    door = models.ForeignKey(
        'Door',
        on_delete=models.CASCADE,
        related_name='orders',
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self.generate_unique_order_number()

        if self.pk is None:
            super(Order, self).save(*args, **kwargs)  # Сначала сохраняем объект

            message = f'Была создана новая заявка от {self.name}.\nТелефон: {self.phone}\nАдрес: {self.address}\nСообщение: {self.message}'
            title = 'Вызов на замер'
            if self.door:
                message += f'\nДверь: {self.door.title}.'
                title = "Новый заказ"

            # Отправка email уведомления
            send_mail(
                title,
                message,
                settings.DEFAULT_FROM_EMAIL,  # От кого
                ['4109974@inbox.ru'],  # Кому отправляем (ваша же почта)
                fail_silently=False,
            )
        else:
            super(Order, self).save(*args, **kwargs)

    def generate_unique_order_number(self):
        while True:
            order_number = f'ORD-{uuid.uuid4().hex[:8]}'
            if not Order.objects.filter(order_number=order_number).exists():
                return order_number

    def __str__(self):
        return f'От {self.name} ({self.phone}) пришел заказ \
            [{self.order_number}]: {self.message}'


class CustomOrder(models.Model):

    construct_choices = [
        ('0', '1 лист 2 мм + 1 контур уплотнения'),
        ('1', '1 лист 3 мм + 1 контур уплотнения'),
        ('2', '1 лист 4 мм + 1 контур уплотнения'),
        ('3', '2 листа 2 мм + 2 контура уплотнения'),
        ('4', '2 листа 3 мм + 2 контура уплотнения'),
        ('5', '2 листа 4 мм + 2 контура уплотнения'),
        ('1.6', 'Цельноугольный лист 1.5 мм + полотно 70 мм'),
        ('7', 'Цельноугольный лист 1.5 мм, противосъемная'),
        ('8', 'Противопожарная'),
    ]

    glazing_choices = [

web/forms.py
from captcha.fields import CaptchaField
from django import forms

from .models import CallBack, CustomOrder, GetDiscount, Order, Review


class CallBackForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = CallBack
        fields = ['name', 'phone', 'captcha']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'phone_mask',
                'placeholder': '+7 (___) ___-__-__'
            }),
        }


class GetDiscountForm(forms.ModelForm):
    class Meta:
        model = GetDiscount
        fields = ['phone',]
        widgets = {
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'phone_mask',
                'placeholder': '+7 (___) ___-__-__',

            }),
        }


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'phone', 'call_time', 'address', 'message']
        widgets = {
            'call_time': forms.DateTimeInput(
                attrs={'type': 'datetime-local', 'class': 'form-control'}
            ),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'phone_mask',
                'placeholder': '+7 (___) ___-__-__'
            }),
            'address': forms.TextInput(
                attrs={'class': 'form-control', 'rows': 3}
            ),
            'message': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3}
            ),
        }


class ReviewForm(forms.ModelForm):
    order_number = forms.CharField(
        max_length=255,
        label="Номер заказа",
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Номер заказа'}
            )
        )

    def clean_order_number(self):
        order_number = self.cleaned_data.get('order_number')
        if not Order.objects.filter(order_number=order_number).exists():
            raise forms.ValidationError("Заказ с таким номером не существует.")
        return order_number

    class Meta:
        model = Review
        fields = ['name', 'message', 'rating', 'order_number']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}
            ),
            'message': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 3,
                    'placeholder': 'Ваш отзыв'
                }
            ),
            'rating': forms.RadioSelect(attrs={'class': 'form-check-input'})
        }


class CustomOrderForm(forms.ModelForm):
    class Meta:
        model = CustomOrder
        fields = '__all__'
        widgets = {
            'type_contruction': forms.Select(attrs={'class': 'form-control'}),
            'double_glazing': forms.Select(attrs={'class': 'form-control'}),
            'out_cover': forms.Select(attrs={'class': 'form-control'}),
            'in_cover': forms.Select(attrs={'class': 'form-control'}),
            'platbans': forms.Select(attrs={'class': 'form-control'}),
            'top_castle': forms.Select(attrs={'class': 'form-control'}),
            'bot_castle': forms.Select(attrs={'class': 'form-control'}),
            'cylinder': forms.Select(attrs={'class': 'form-control'}),
            'hinge': forms.Select(attrs={'class': 'form-control'}),
            'blockers': forms.Select(attrs={'class': 'form-control'}),
            'insulation': forms.Select(attrs={'class': 'form-control'}),
            'dismantling': forms.Select(attrs={'class': 'form-control'}),
            'night_lock': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            ),
            'peephole': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            ),
            'door_closer_100kg': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            ),
            'door_closer_120kg': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            ),
            'handle_scarf': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            ),
        }

templates/pages/blog_chapter.html
{% extends '../index.html' %}

<link rel="canonical" href="/blog/" />
{% block title %}
Выбрать раздел | Паритет двери
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a class="link-dark" href="{% url 'index' %}">Главная</a></li>
      <li class="breadcrumb-item active" aria-current="page">Блог</li>
    </ol>
</nav>
  
<section class="row d-flex mt-3 justify-content-center">
    {% for chapter, count in chapters.items %}
    <div class="col-lg-3 col-8 m-2 image-container p-0 rounded-5">
        <a href="{% url 'blog_chapter_detail' chapter.slug %}">
            <div class="background-image w-100" style="background-image: linear-gradient(to top, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0)), url('{{ chapter.image.url }}');"></div>
            <div class="overlay p-3 text-white d-flex flex-column" style="position: absolute; bottom: 0; left: 0; width: 100%;">
                <div class="mt-auto text-center">
                    <p class="m-0">{{ chapter.title }}</p>
                    <p class="small" style="color: silver;">Блогов в этом разделе {{count}}</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</section>

<style>
.image-container {
    position: relative;
    overflow: hidden;
    height: 300px;
}

.background-image {
    background-size: cover;
    background-position: center;
    width: 100%;
    height: 100%;
    transition: transform 0.5s ease;
}

.image-container:hover .background-image {
    transform: scale(1.1);
}
</style>
{% endblock content %}

templates/pages/blog_chapter_detail.html
{% extends '../index.html' %}
<link rel="canonical" href="/blog/{{ chapter.slug }}/" />

{% block title %}
Раздел {{ chapter.title }} | Паритет двери
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a class="link-dark" href="{% url 'index' %}">Главная</a></li>
      <li class="breadcrumb-item"><a class="link-dark" href="{% url 'blog_chapter' %}">Блог</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ chapter.title }}</li>
    </ol>
</nav>

<section class="container mt-3">
    <div class="text-center mb-4">
        <h1>{{ chapter.title }}</h1>
        <img src="{{ chapter.image.url }}" alt="{{ chapter.title }}" class="img-fluid mb-3">
    </div>
    <div class="row d-flex justify-content-center">
        {% for blog in blogs %}
        <div class="col-lg-4 col-10 my-2">
            <a href="{% url 'blog_post_detail' chapter.slug blog.slug %}" class="text-decoration-none">
                <div class="card h-100 rounded-top-5" style="overflow: hidden;">
                    <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}" style="max-height: 250px; width: 100%; object-fit: cover; object-position: center;">
                    <div class="card-body">
                        <p class="text-secondary">{{ blog.created_at }}</p>
                        <p class="h5">{{ blog.title }}</p>
                        <p class="card-text text-secondary">{{ blog.content|truncatewords:20|striptags }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% empty %}
        <p class="text-center">Нет блогов в этой главе.</p>
        {% endfor %}
    </div>
</section>

{% endblock content %}

templates/pages/blog_post_detail.html
{% extends '../index.html' %}

<link rel="canonical" href="/blog/{{ chapter.slug }}\{{ blog.slug }}/" />
{% block title %}
Блог {{ blog.title }} | Паритет двери
{% endblock %}

{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a class="link-dark" href="{% url 'index' %}">Главная</a></li>
        <li class="breadcrumb-item"><a class="link-dark" href="{% url 'blog_chapter' %}">Блог</a></li>
        <li class="breadcrumb-item"><a class="link-dark" href="{% url 'blog_chapter_detail' chapter.slug %}">{{ chapter.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ blog.title }}</li>
    </ol>
</nav>
{{ blog.content|safe }}
{% endblock content %}

templates/pages/installation.html
{% extends '../index.html' %}

<link rel="canonical" href="/installation/" />

{% block title %}
Установка | Паритет двери
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a class="link-dark" href="{% url 'index' %}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Установка</li>
  </ol>
</nav>
<h1 class="my-3 text-center">Установка входных дверей</h1>
<label class="mt-2" style="font-family: tilda-medium;">
    <p>Установка входных металлических дверей осуществляется штатными специалистами.
    Время установки заранее согласовывается с Заказчиком.
    Гарантия распространяется на услуги по установке, если она выполнялась мастерами Паритет-Двери.
    Подробнее об условиях предоставления гарантии <a class="link link-dark" href="{% url 'garant' %}">читайте здесь.</a></p>
</label>
<section class="row d-flex">
  <ul class="list-group text-center my-4 col-lg-6">
    <li class="list-group-item text-center text-light" style="background-color: crimson;">Перечень услуг по установке дверей</li>
    <li class="list-group-item">Замер и подготовка дверного проема</li>
    <li class="list-group-item">Демонтаж старой двери</li>
    <li class="list-group-item">Установка входной двери</li>
    <li class="list-group-item">Регулировка фурнитуры</li>
    <li class="list-group-item">Оформление гарантии</li>
    <li class="list-group-item">Консультации</li>
  </ul>
  <ul class="list-group text-center my-4 col-lg-6">
    <form method="POST" action="{% url 'installation' %}">
      <li class="list-group-item text-center text-light mb-2" style="background-color: crimson;">Расчет стоимости услуг</li>
      {% csrf_token %}
      <section class="row">
        <div class="mb-3 col-6">
          <label for="id_name">Имя</label>
          {{ form.name }}
        </div>
        <div class="mb-3 col-6">
          <label for="id_phone">Телефон</label>
          {{ form.phone }}
        </div>
        <div class="mb-3 col-6">
          <label for="id_call_time">Время звонка</label>
          {{ form.call_time }}
        </div>
        <div class="mb-3 col-6">
          <label for="id_address">Адрес</label>
          {{ form.address }}
        </div>
        <div class="mb-3">
          <label for="id_message">Сообщение</label>
          {{ form.message }}
        </div>
      </section>
      <button type="submit" class="btn btn-danger">Оставить заявку</button>
    </form>
  </ul>
</section>
<table class="table text-center border">
  <thead>
    <tr>
      <th scope="col" class="bg-danger text-light">Услуга</th>
      <th scope="col" class="bg-danger text-light">Стоимость</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Монтаж металлической двери в готовый проем</td>
      <td>5000 руб. При заказе монтажа, доставка бесплатно!</td>
    </tr>
    <tr>
      <td>Монтаж двустворчатой металлической двери в готовый проем</td>
      <td>6000 руб.</td>
    </tr>
    <tr>
      <td>Расширение кирпичного проема до 5 см в одну сторону</td>
      <td>1500 руб.</td>
    </tr>
    <tr>
      <td>Расширение бетонного проема до 5 см в одну сторону</td>
      <td>1500 руб.</td>
    </tr>
    <tr>
      <td>Расширение монолитного проема до 5 см в одну сторону</td>
      <td>2000 руб.</td>
    </tr>
    <tr>
      <td>Подъем двери весом до 100кг/более 100кг на этаж, без лифта</td>
      <td>250/350 руб/этаж</td>
    </tr>
    <tr>
      <td>Демонтаж деревянной рамы с фрамугой</td>
      <td>1800 руб.</td>
    </tr>
    <tr>
      <td>Демонтаж старой металлической двери</td>
      <td>1500 руб.</td>
    </tr>
    <tr>
      <td>Монтаж с применением сварочных работ («уши», штыри), за 1 сторону (с учетом материала)</td>
      <td>1500 руб.</td>
    </tr>
    <tr>
      <td>Запенивание и герметизация монтажных зазоров</td>
      <td>бесплатно</td>
    </tr>
    <tr>
      <td>Уборка мусора после монтажа без его выноса</td>
      <td>бесплатно</td>
    </tr>
  </tbody>
</table>
<section class="vstack col-12 col-lg-8 mx-auto text-center">
    <section>
      <i class="bi bi-1-square" style="font-size: 50px;"></i>
      <p class="lh-1" style="font-size: 30px">Замер</p>
      <label class="text-secondary text-start">
        Для записи на замер Вы можете:<br>
        позвонить по телефонам: +7 (499) 322-91-25;
        оставить заявку, воспользовавшись специальной формой;
        написать нам со страница Контакты. 
      </label>
    </section>
    <section>
      <i class="bi bi-2-square" style="font-size: 50px;"></i>
      <p class="lh-1" style="font-size: 30px">Доставка</p>
      <label class="text-secondary text-start">
        Доставка готовой двери осуществляется в течение 1–3 дней.
        Готовую конструкцию для транспортировки упаковывают в пленку или в гофрокартон.
        Более подродно о регионах и стоимости доставки в разделе Доставка.
      </label>
    </section>
    <section>
      <i class="bi bi-3-square" style="font-size: 50px;"></i>
      <p class="lh-1" style="font-size: 30px">Монтаж</p>
      <label class="text-secondary text-start">
        В основные этапы монтажа двери входят:
        очистка проёма, демонтаж, примерка и выравнивание, фиксация, запенивание
      </label>
    </section>
    <section>
      <i class="bi bi-4-square" style="font-size: 50px;"></i>
      <p class="lh-1" style="font-size: 30px">Приемка работ</p>
      <label class="text-secondary text-start">
        Заранее до начала работ осмотрите полотно на наличие сколов и царапин.
        После установки и регулировки проверьте фурнитуру: ручки должны легко поддаваться,
        ригеля замков беспрепятственно входить в отверстия коробки, а вертушка
        замка проворачиваться без усилий.
        Проверьте места стыковки доборов с коробкой: там не должно быть
        сколов и больших щелей.
        Дверь в открытом состоянии должна оставаться на месте.
        Дверное полотно должно плотно прилегать к коробке, не болтаться и не искривляться
        при закрывании. Никаких скрипов и постороннего шума.
      </label>
    </section>
</section>
<h4 class="text-center my-4 mx-auto">
  <span class="badge text-bg-danger">Важно!</span>
  Обязательно подписывайте акт приемки работ.
  На основании акта предоставляются услуги гарантийного обслуживания. 
</h4>
<section>
  <label class="text-start">
    Монтажники приезжают в условленный день со всеми необходимыми
    инструментами, справятся за час или полтора. Распашные двери усаживают на саморезы,
    прикручивают через петли. При помощи клиньев выстраивают коробку.
    Брусья спиливают под углом, верхний полностью, у боковых только передняя часть.
    Чтобы не ошибиться с выбором, при покупке межкомнатной двери стоит учесть такие
    факторы, как размер проема, материал двери, ее покрытие и наполнение. 
    Разобраться со всеми тонкостями помогут специалисты Интернет-магазина Paritet-dveri.ru.
  </label>
</section>
{% endblock content %}